export const CHANGE_LOADING_MSG = 'CHANGE_LOADING_MSG'
export const CHANGE_LOADING_STATE = 'CHANGE_LOADING_STATE'
export const SET_ACCOUNT_INFO = 'SET_ACCOUNT_INFO'
export const UPDATE_LOG_MSG = 'UPDATE_LOG_MSG'
